### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by tidusblitzace** [MalcolmA/Supreme#1]
It says "Value cannot be null. Parameter Name: solution directory"

**Comment by MalcolmA** [comment]
Hi,

please state more information about the issue (e. g. how have you built the code?)

Reading the error message, I assume the error is caused by a wrong configured development environment and not by the code itself.

Best Regards,

Malcolm

**Comment by MalcolmA** [comment]
Again successfully tested on march 23rd 11am ldn time drop. Works fine from here.

**Comment by tidusblitzace** [comment]
What's your skype? It's not working for me.

**Comment by MalcolmA** [comment]
This version worked for Supreme x The North Face today at 11am ldn time. Sorry, I won't be able to give personal support via Skype in the near future. Nevertheless you can ask your questions, but you have to be more precise.

I will upload a library version (+example GUI) of this in the next few days anyways which will be more easy to understand. But if you already have trouble building this code, that won't help you out either.

**Comment by MalcolmA** [comment]
Discontinued due to Google ReCaptcha.
